### ISSUE TITLE
What the relationship with harbor？

### ISSUE THREAD

**Issue by lurenjia528** [uber/kraken#140]
kraken  and   docker-registry  and  harbor   
for example : 
  when i use kubernetes, I use harbor first, if i want to use kraken, should i delete all harbor?
  Is kraken == docker-registry == harbor  ?

**Comment by yiranwang52** [comment]
Kraken can use other registries as backend.
Please take a look at the documentation:
https://github.com/uber/kraken/blob/master/docs/CONFIGURATION.md#configuring-storage-backend-for-origin-and-build-index

We haven't tried Harbor ourselves, but it should work.

**Comment by qinzhao168** [comment]
[root@ cdstest]# uname -a 
 3.10.0-327.4.5.el7.x86_64 #1 SMP Mon Jan 25 22:07:14 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

[root@qinzhao-build-env cdstest]# docker-compose up --no-recreate cds-migrate 
Starting cdstest_cds-db_1 ... done
Starting cdstest_cds-migrate_1 ... done
Attaching to cdstest_cds-migrate_1
cds-migrate_1         | There are 157 migrate files locally. Current engine needs 157 files
cds-migrate_1         | Error: dial tcp: i/o timeout
cds-migrate_1         | 
cdstest_cds-migrate_1 exited with code 1
