### ISSUE TITLE
how to  delete images(gc)

### ISSUE THREAD

**Issue by lmdkfs** [uber/kraken#146]
how to  delete images ？ what about the  speed  ?

**Comment by codygibb** [comment]
Image deletion is not supported.

To delete an image, we would need to support manifest->layer reference counting to ensure we don't delete a shared layer that is still in use. Unfortunately we would need to acquire a global lock on all tag/blob data to calculate reference counts, which is unsupported in many blob backends (e.g. s3) and thus this problem remains unsolved.

If image gc is something you need, you could manage your images with a registry backend that supports gc, and just use kraken as a distribution layer.
