### ISSUE TITLE
Compile master failed

### ISSUE THREAD

**Issue by mmpei** [uber/kraken#148]
see the dependancy from glide.yaml
```
- package: github.com/docker/distribution
  version: ^2.6.2
```
this means the package could be >=2.6.2 && <3.0.0.
actually compile master branch will be failed if using v2.6.2 because registry v2.7.0 is not compatible with v2.6.2.
so these dependancy could be defined more exactly.

**Comment by yiranwang52** [comment]
hmm glide.lock pinned the version (2.7.1), so I don't think this is still an issue. Maybe you were using an older version of golang?

We were using 2.6.2, so this move to 2.7.1 is a little risky, but that's a separate issue.
