### ISSUE TITLE
Have the agent usable in GCP

### ISSUE THREAD

**Issue by bpaquet** [uber/kraken#187]
Hello,

In my GKE cluster (standard configuration, no tuning), I have to change some stuff to have the agent usable
- use 127.0.0.1:30081 instead of localhost:30081
- Adding allow 10.0.0.0/8; here: https://github.com/uber/kraken/blob/master/nginx/config/agent.go#L27

Am I missing something ?
I think the agent should be able to work on GKE without recompiling. Can I add a param somewhere to pass the CIDR to allow in the config ?

**Comment by yiranwang52** [comment]
Sure, it's totally okay to make that configurable.
