### ISSUE TITLE
Is there a "how to get started with kraken" guide?

### ISSUE THREAD

**Issue by NikiChr** [uber/kraken#202]
I want to use kraken in my master thesis where I evaluate image distribution systems in a virtual network that I create with containernet.

However I am having difficulties setting up or rather even getting started with kraken.
I am not that experienced with image or file distribution systems and could really use a step-by-step guide for getting started with deploying kraken in a network.
I am already successfully using dragonfly and a "how to get started" guide for kraken like dragonfly's [quick start](https://github.com/dragonflyoss/Dragonfly/tree/master/docs/quick_start) and their [user guide](https://github.com/dragonflyoss/Dragonfly/tree/master/docs#User-Guide) could be helpful for others too.

So far I did

1. `git clone https://github.com/uber/kraken.git`

2. `cd kraken`

3. and than I am pretty much lost since `make devcluster` does not work. I am working in a linux environment and I already applied the change documented in #71.

I am thankful for any help I can get!

**Comment by yiranwang52** [comment]
On one side, yes we need to improve documentaiton;
On the other side, can you explain which part failed with devcluster?

**Comment by NikiChr** [comment]
The host has the kraken.git and the adjusted .yaml files for linux.
`cd kraken` then `make devcluster` results in the following:
```
go get -u github.com/Masterminds/glide
/bin/glide i
/bin/bash: /bin/glide: No such file or directory
make: *** [Makefile:97: vendor] Error 127
```
I want to use kraken in a mininet/containernet network.
However since I am not experienced in setting up such networks I am in need of some kind of instruction for each kraken component.

**Comment by yiranwang52** [comment]
glide is dependency management tool used by Go. You need to install that.

Separately I think it's better we provide some scripts to allow you to run the project without compiling it.

**Comment by NikiChr** [comment]
I added glide in my dockerfile however I needed to use `glide install`.
Now I get this error message:
```
bash-5.0# make devcluster
docker run --rm -it -v :/go -w /go/src/github.com/uber/kraken golang:1.11.4 go build -o ./agent/agent ./agent/
Unable to find image 'golang:1.11.4' locally
1.11.4: Pulling from library/golang
ab1fc7e4bf91: Pull complete 
35fba333ff52: Pull complete 
f0cb1fa13079: Pull complete 
3d1dd648b5ad: Pull complete 
866ed2e2b1fe: Pull complete 
85221581e349: Pull complete 
0b7ee073a53e: Pull complete 
Digest: sha256:4469b68518ffcae4cc1f5310752495c3ed53c039e28f1638b23c21f1fc7a54cf
Status: Downloaded newer image for golang:1.11.4
can't load package: package github.com/uber/kraken/agent: cannot find package "github.com/uber/kraken/agent" in any of:
	/usr/local/go/src/github.com/uber/kraken/agent (from $GOROOT)
	/go/src/github.com/uber/kraken/agent (from $GOPATH)
failed to resize tty, using default size
make: *** [Makefile:40: agent/agent] Error 1
```

**Comment by yiranwang52** [comment]
I think your go environment has problems...
The easiest solution here is we provide a script to run images directly, instead letting everyone compile the code.

**Comment by NikiChr** [comment]
> I think your go environment has problems...

I think it might have to do with the Docker in Docker containers I use for simulations.

> The easiest solution here is we provide a script to run images directly, instead letting everyone compile the code.

Is there already something that I can use or is it a WIP?

Apart from that I have made some progress and actually got it working by using a slightly different approach, as can be seen in the following dockerfile:

```
FROM docker:dind

RUN apk add --no-cache bash git musl-dev nano make go curl tar \
	&& apk update 
	
# configure go
ENV GOROOT /usr/lib/go
ENV GOPATH /go
ENV PATH /go/bin:$PATH
RUN mkdir -p ${GOPATH}/src ${GOPATH}/bin ${GOPATH}/src/github.com/uber

# install glide
RUN go get -u github.com/Masterminds/glide/...

# install kraken
WORKDIR $GOPATH/src/github.com/uber/
RUN git clone https://github.com/uber/kraken
WORKDIR $GOPATH/src/github.com/uber/kraken
RUN glide install
COPY content1/ /$GOPATH/src/github.com/uber/kraken
#COPY content2/ /$GOPATH/src/github.com/uber/kraken

# install missing packages
RUN go get github.com/andres-erbsen/clock github.com/c2h5oh/datasize github.com/cactus/go-statsd-client/statsd github.com/cenkalti/backoff github.com/docker/distribution/configuration github.com/docker/distribution/context github.com/docker/distribution/registry github.com/docker/distribution/registry/storage/driver github.com/docker/distribution/registry/storage/driver/factory github.com/docker/distribution/uuid github.com/jackpal/bencode-go github.com/pressly/chi github.com/spaolacci/murmur3 github.com/uber-go/tally/m3 github.com/uber-go/tally/statsd github.com/uber-go/tally github.com/willf/bitset go.uber.org/atomic go.uber.org/zap go.uber.org/zap/zapcore golang.org/x/time/rate gopkg.in/validator.v2 gopkg.in/yaml.v2 github.com/uber/kraken/agent github.com/googleapis/gax-go/v2 go.opencensus.io/plugin/ochttp go.opencensus.io/trace go.opencensus.io/trace/propagation github.com/aws/aws-sdk-go/aws   github.com/aws/aws-sdk-go/aws/awserr   github.com/aws/aws-sdk-go/aws/credentials   github.com/aws/aws-sdk-go/aws/session   github.com/aws/aws-sdk-go/service/s3   github.com/aws/aws-sdk-go/service/s3/s3iface   github.com/aws/aws-sdk-go/service/s3/s3manager   github.com/awslabs/amazon-ecr-credential-helper/ecr-login   github.com/awslabs/amazon-ecr-credential-helper/ecr-login/api   github.com/docker/docker-credential-helpers/client   github.com/docker/engine-api/types   github.com/go-chi/chi   github.com/jmoiron/sqlx   github.com/mattn/go-sqlite3   github.com/pressly/goose   github.com/satori/go.uuid   google.golang.org/api/iterator  github.com/garyburd/redigo/redis cloud.google.com/go/storage golang.org/x/oauth2 golang.org/x/oauth2/google
RUN export PACKAGE_VERSION=myversion
#RUN make devcluster
	
ENTRYPOINT ["dockerd-entrypoint.sh"]
CMD /bin/bash
```
I than have to manually execute `make devcluster` inside my dind container.
Otherwise when I try to execute it via the dockerfile it produces the following error:
```
the input device is not a TTY
make: *** [Makefile:40: agent/agent] Error 1
```
Again I can imagine that this is due to Docker in Docker.

When I follow [the instruction on `make devcluster`](https://github.com/uber/kraken/tree/master/examples/devcluster) I receive this error in step 2:
```
bash-5.0# docker pull localhost:16000/library/golang:1.11
Error response from daemon: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>nginx/1.10.3</center>\r\n</body>\r\n</html>\r\n"
```

**Comment by yiranwang52** [comment]
Would "[Kraken on k8s](https://github.com/uber/kraken#kraken-on-kubernetes)" setup work for you?

**Comment by NikiChr** [comment]
I think k8s is too much for my purpose.

For setting up kraken I use a very simple and small virtual network via containernet with 4 containers/hosts in a ring architecture:
- r1:`44.44.12.1`
- r2:`44.44.12.2`
- r3:`44.44.13.3`
- r4:`44.44.24.4`

My plan was to run a tracker container, origin container, proxy and build-index container on r1 and an agent container on r2, r3 and r4 just for testing by pulling and pushing some docker images in the network.
I was hoping I can setup kraken by just executing _docker run_ for each container on each host and adjusting some config files.
Afterwards the results shall be used to setup kraken in a larger virtual network that also runs with containernet.

Now that I have the docker image for each component I should be able to setup up kraken in my small network by importing the images (into the hosts) and the kraken.git (into each host's $GOPATH), right?

Since I can not handle docker so well yet, I was hoping to find the necessary instructions in the documentation on: 

**1. what to download.
2. which files/configs to modify. 
3. how to start the containers.
4. how to check if kraken works as intendet.**

Maybe that describes my current situation better and sheds some clarity on my issue.
I am sorry if I did not express my issue sufficiently till now.
