### ISSUE TITLE
Uploading & downloading blobs 

### ISSUE THREAD

**Issue by namespaceXP** [uber/kraken#204]
I've got some questions on uploading & downloading blobs.

1. For what reason the blobs must be uploaded in chunks? How should the blobs be divided into chunks?

2. Is it possible to alter the content of an uploaded blob?   Can we simply re-upload the relevant chunk?

3. Is it possible to download only one chunk of an uploaded blob?

**Comment by yiranwang52** [comment]
1. It's configurable, you don't have to. It's encouraged because when error happen, the failed chunk can be retried, instead of re-uploading the whole blob.

2. No, everything is content addressable, no mutation allowed. If you have the uuid returned from previous upload, you should be able to resume upload.

3. I don't think so.

**Comment by namespaceXP** [comment]
Another question, after running 'make devcluster', which seems to be alright, I got an error response from 'docker pull localhost:16000/library/golang:1.11':

Error response from daemon: Get https://localhost:16000/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

I wonder what's the problem.

**Comment by yiranwang52** [comment]
are you able to connect to DockerHub? could be a problem specific to your physical location.

**Comment by namespaceXP** [comment]
I've solved the connection problem but now every time I tried to push/pull an image I got an 500 error such as:

$ docker push localhost:15000/library/hello-world
The push refers to repository [localhost:15000/library/hello-world]
af0b15c8625b: Layer already exists 
[DEPRECATION NOTICE] registry v2 schema1 support will be removed in an upcoming release. Please contact admins of the localhost:15000 registry NOW to avoid future disruption.
received unexpected HTTP status: 500 Internal Server Error

**Comment by namespaceXP** [comment]
xpdeMacBook-Pro:kraken xp$ docker push localhost:15000/library/hello-world
The push refers to repository [localhost:15000/library/hello-world]
af0b15c8625b: Layer already exists 
[DEPRECATION NOTICE] registry v2 schema1 support will be removed in an upcoming release. Please contact admins of the localhost:15000 registry NOW to avoid future disruption.
received unexpected HTTP status: 500 Internal Server Error
xpdeMacBook-Pro:kraken xp$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                            NAMES
d6f9c136721d        kraken-agent:dev    "/usr/bin/kraken-age…"   23 minutes ago      Up 23 minutes       0.0.0.0:17000-17002->17000-17002/tcp                             kraken-agent-two
02dfc2bd5a6c        kraken-agent:dev    "/usr/bin/kraken-age…"   23 minutes ago      Up 23 minutes       0.0.0.0:16000-16002->16000-16002/tcp                             kraken-agent-one
cb3031e3f4ce        kraken-herd:dev     "./herd_start_proces…"   24 minutes ago      Up 23 minutes       0.0.0.0:14000->14000/tcp, 0.0.0.0:15000-15005->15000-15005/tcp   kraken-herd
xpdeMacBook-Pro:kraken xp$ docker logs cb3031e3f4ce
7:C 27 Aug 2019 06:12:38.872 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
7:C 27 Aug 2019 06:12:38.872 # Redis version=5.0.5, bits=64, commit=00000000, modified=0, pid=7, just started
7:C 27 Aug 2019 06:12:38.872 # Configuration loaded
7:M 27 Aug 2019 06:12:38.873 * Running mode=standalone, port=14001.
7:M 27 Aug 2019 06:12:38.873 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
7:M 27 Aug 2019 06:12:38.873 # Server initialized
7:M 27 Aug 2019 06:12:38.873 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
7:M 27 Aug 2019 06:12:38.873 * Ready to accept connections
xpdeMacBook-Pro:kraken xp$
