### ISSUE TITLE
400 Error while uploading blobs into origin_cluster

### ISSUE THREAD

**Issue by namespaceXP** [uber/kraken#207]
While running the integration test, I got an 400 error:

HTTPError: 400 Client Error: Bad Request for url: https://localhost:63184/namespace/testfs/blobs/sha256:bee0eb797e03f29745f581a1a81e58f4e378c0160870f45156210c8557cff695/uploads

**Comment by yiranwang52** [comment]
are you running on latest master?

**Comment by namespaceXP** [comment]
Yes, I think so.
