### ISSUE TITLE
Timeout when pull large layers(about 1G)

### ISSUE THREAD

**Issue by yiduyangyi** [uber/kraken#208]
**Describe the bug**
hi  all,
I use the master branch fdd12760abe0f4acd59d3fb601c10fd8f0a5ff92 today compiled and build images of kraken, then helm install it into an existing kubernetes cluster. configue an existing registry as kraken's backend

when i pull an image with 4 layers(three large layers, each is 1G, gengrated by dd, and one small layer about 50M ) use 127.0.0.1:30081/bm-jpaas/bigimage:latest, the small layer pulled succeed while the large ones timeouts in origin.

when i pull the image from the backend registry directly, there is no problem

can someone help?

**To Reproduce**
compile the master branch fdd12760abe0f4acd59d3fb601c10fd8f0a5ff92 and helm install it in a k8s cluster, the pull an image with large layer such as 1G from 127.0.0.1:30081

**Expected behavior**
the image pull success from agent when it's first pulled

**Screenshots**
![image](https://user-images.githubusercontent.com/16739638/64688244-857dce00-d4be-11e9-99e4-77ab047e7dd1.png)

![image](https://user-images.githubusercontent.com/16739638/64688311-ae9e5e80-d4be-11e9-9e32-3744e72ed271.png)

**Environments**
kubernetes: 1.13.10
docker: 18.09.2

**Additional context**

**Comment by yiranwang52** [comment]
Seems like origin received 500 error when pulling from your registry.  
What are you using for your backend registry? Does it enforce some kind of throttling?

**Comment by rarchk** [comment]
did any resolution came on this one ?

**Comment by rarchk** [comment]
I'm using harbor registry. I found that for smaller images kraken setup works. But for images with large layers, I'm facing issues. I tried increasing timeout, but nothing happened.

**Comment by yiranwang52** [comment]
@rarchk normally it's problem on the backend side (harbor in this case)
