### ISSUE TITLE
Tracker gauge count value is always one

### ISSUE THREAD

**Issue by EltonzHu** [uber/kraken#214]
**Describe the bug**
Variable count is a local variable inside if scope.
https://github.com/uber/kraken/blob/6fc30641f33bce8ea21febe0dc2aac9d0f55c16d/tracker/peerhandoutpolicy/peerhandoutpolicy.go#L85

https://github.com/uber/kraken/blob/6fc30641f33bce8ea21febe0dc2aac9d0f55c16d/tracker/peerhandoutpolicy/peerhandoutpolicy.go#L92 count is always one.

**To Reproduce**
You can setup a metric monitoring system, you can see tracker gauge count metric is always one.

**Expected behavior**
We want to get the number of occurrence with different labels. 
priorityCounts[p.label] should be incremented rather than local variable count. 

**Environments**
GCP and Data centers

**Comment by EltonzHu** [comment]
This bug is fixed in PR #215

**Comment by yiranwang52** [comment]
Thanks for the fix!
