### ISSUE TITLE
Does Kraken support P2P Peer Optimal Algorithm based on network topology awareness?

### ISSUE THREAD

**Issue by duyanghao** [uber/kraken#244]
I am curious about whether Kraken supports P2P Peer Optimal Algorithm, guess Peer1 can get data from neither Peer2 or Peer3, and Peer2 is closer to Peer1 with regard to network topology, will Peer1 finally choose the Peer2 instead of Peer3?

**Comment by yiranwang52** [comment]
Kraken is aware of underlying network topology as of today.

We tried a simple implementation in early days, but that had severe negative impact on performance. My theory is - assume group A and group B are far way, and both want the same image. Group A started downloading a couple seconds earlier, and occupied all open connections on origin cluster. Group B peers cannot reach origin, and were not recommended to talk to group A, so they just connect among themselves, and cannot get any data. Group B peers were only able to make progress after most of group A finished downloading.

Then we opt for having separate clusters in each physical zone, and let them share storage or setup replication.

If you are curious, it's easy to extend tracker implementation by adding new policies, or write some simple simulations.

**Comment by duyanghao** [comment]
> Kraken is aware of underlying network topology as of today.
> 
> We tried a simple implementation in early days, but that had severe negative impact on performance. My theory is - assume group A and group B are far way, and both want the same image. Group A started downloading a couple seconds earlier, and occupied all open connections on origin cluster. Group B peers cannot reach origin, and were not recommended to talk to group A, so they just connect among themselves, and cannot get any data. Group B peers were only able to make progress after most of group A finished downloading.
> 
> Then we opt for having separate clusters in each physical zone, and let them share storage or setup replication.
> 
> If you are curious, it's easy to extend tracker implementation by adding new policies, or write some simple simulations.

@yiranwang52 Thanks for your reply, Is there any more detailed design documents about your theory implement, I want to learn more about this.

**Comment by yiranwang52** [comment]
Currently kraken doesn't support this at all. Since our simple approach didn't work, we removed the code.

**Comment by duyanghao** [comment]
@yiranwang52 What's the plan for this feature? or doesn't kraken want to support it at all?

**Comment by yiranwang52** [comment]
Uber probably wouldn't need this, given how we design zones and regions. If any contributor can make it work as an option with convincing data, then we will glad to merge it in.

**Comment by duyanghao** [comment]
@yiranwang52 Thanks for your reply. Close this issue since now I have no idea about this.
