### ISSUE TITLE
how to import layer blobs to docker daemon use puller tool with http method

### ISSUE THREAD

**Issue by Gsealy** [uber/kraken#264]
**Describe the bug**
use [puller](https://github.com/uber/kraken/blob/master/tools/bin/puller/main.go) tool with http download, just download the image to memory, not load in docker daemon

**To Reproduce**
run a docker registry in `localhost:5000`, and push a test image

```shell
docker run -d -p 5000:5000 --restart always -e REGISTRY_STORAGE_DELETE_ENABLED="true" --name registry registry:2.7
docker push localhost:5000/nginx:1.16.0
```

build puller and run it. 

```shell
./puller -source localhost:5000 -image nginx:1.16.0
2020-06-16T09:58:37.231+0800	info	puller/main.go:39	pulling image from infosec:5000/nginx:1.16.0
2020-06-16T09:58:37.231+0800	info	puller/pull.go:61	pulling with http
2020-06-16T09:58:37.327+0800	info	puller/pull.go:95	finished pulling image nginx:1.16.0 in 0.09615146
```

**Expected behavior**
`docker images` can show it

**Screenshots**
see Reproduce

**Environments**
e.g CentOS Server

**Additional context**
this tools maybe not finished, How to import blobs to localhost docker daemon without docker client?
I want to use http pull image and load it. 

Thanks.

**Comment by yiranwang52** [comment]
the tool is just used for testing kraken. why not just use docker pull?

**Comment by Gsealy** [comment]
the first think was HTTP API with async speed will better than docker pull.
I will use docker pull, thanks for reply.
