### ISSUE TITLE
Update contact information

### ISSUE THREAD

**Issue by wk8** [uber/kraken#290]
**Describe the bug**
The REAME says that anyone can join your Slack channel to be able to reach maintainers (https://github.com/uber/kraken#contact). However, it seems that that Slack channel does not support guest accounts, nor does it allow new users to sign up with a non-uber.com email address.

**To Reproduce**
Steps to reproduce the behavior: follow that link.

**Expected behavior**
I'd like to be able to reach out to maintainers :)

**Comment by aryanvarma7272** [comment]
@wk8 , how can i solve this issue ?

**Comment by wk8** [comment]
@aryanvarma7272 I don't know, been a minute :) closing
