### ISSUE TITLE
GoModules problem with go-sqlmock

### ISSUE THREAD

**Issue by im-kulikov** [uber/kraken#88]
https://github.com/DATA-DOG/go-sqlmock/issues/166#issuecomment-470174499

Module has wrong name. What you think, mb we can upgrade to new release?

**Comment by im-kulikov** [comment]
go-sqlmock v1.3.2 has wrong module name and ‘go mod init’ fails with unknown dependency

Go 1.11.x / 1.12.x
GoModules

**Comment by im-kulikov** [comment]
Fixed in new release - https://github.com/DATA-DOG/go-sqlmock/tree/v1.3.3

**Comment by apourchet** [comment]
I believe we no longer have DATA-DOG/go-sqlmock in our module dependencies. Are you still having the issue with latest master 3bca40a660c0da0a381b84865af3ad3c623283f3 @im-kulikov ?

**Comment by im-kulikov** [comment]
Not tested yet.. I’ll try on this Monday

**Comment by im-kulikov** [comment]
@apourchet oh, thanks.. it's works now.
I hope my observations were useful..
can be closed

**Comment by yiranwang52** [comment]
Thanks.
