### ISSUE TITLE
 Checksum missmuch is at github.com/apache/thrift

### ISSUE THREAD

**Issue by kodomo898** [uber/kraken#93]
The following error is displayed after executing make image

**go: verifying github.com/apache/thrift@v0.0.0-20161221203622-b2a4d4ae21c7: checksum mismatch
        downloaded: h1:Fv9bK1Q+ly/ROk4aJsVMeuIwPel4bEnD8EPiI91nZMg=
        go.sum:     h1:CZI8h5fmYwCCvd2RMSsjLqHN6OqABlWJweFKxz4vdEs=
make: *** [agent/agent] Error 1**

I would like to modify go.sum as follows
**-github.com/apache/thrift v0.0.0-20161221203622-b2a4d4ae21c7 h1:CZI8h5fmYwCCvd2RMSsjLqHN6OqABlWJweFKxz4vdEs=
+github.com/apache/thrift v0.0.0-20161221203622-b2a4d4ae21c7 h1:Fv9bK1Q+ly/ROk4aJsVMeuIwPel4bEnD8EPiI91nZMg=**

**Comment by yiranwang52** [comment]
Hmm could be a go version problem. Let me revert the latest commit.

**Comment by yiranwang52** [comment]
Should be fine now.

**Comment by kodomo898** [comment]
Thanks for quick response!

**Comment by surapuramakhil** [comment]
Hie I am still getting this issue. My forked repo is up to date with the origin.
but a different error status.
bellow is error message

192:kraken akhil$ make vendor
GO111MODULE=on go mod vendor
go: downloading github.com/aws/aws-sdk-go v1.17.6
go: downloading github.com/apache/thrift v0.0.0-20161221203622-b2a4d4ae21c7
go: downloading gopkg.in/square/go-jose.v1 v1.1.1
go: verifying github.com/apache/thrift@v0.0.0-20161221203622-b2a4d4ae21c7: checksum mismatch
	downloaded: h1:CZI8h5fmYwCCvd2RMSsjLqHN6OqABlWJweFKxz4vdEs=
	go.sum:     h1:Fv9bK1Q+ly/ROk4aJsVMeuIwPel4bEnD8EPiI91nZMg=
make: *** [vendor] Error 1

**Comment by yiranwang52** [comment]
@surapuramakhil what's your go version?

**Comment by surapuramakhil** [comment]
akhil:~ akhil$ go version
go version go1.11.1 darwin/amd64

**Comment by yiranwang52** [comment]
do you mind trying a newer version of Go and let us know? since we do not see this issue on either travis-ci or our laptops.

**Comment by surapuramakhil** [comment]
updating go has worked. thanks 👍

**Comment by sagar1009** [comment]
Hey, I'm still getting this issue 
My go version
go version go1.11.3 darwin/amd64

Error is : 
go: verifying github.com/apache/thrift@v0.0.0-20161221203622-b2a4d4ae21c7: checksum mismatch
	downloaded: h1:CZI8h5fmYwCCvd2RMSsjLqHN6OqABlWJweFKxz4vdEs=
	go.sum:     h1:Fv9bK1Q+ly/ROk4aJsVMeuIwPel4bEnD8EPiI91nZMg=

Please suggest.

**Comment by sagar1009** [comment]
updated to 1.12.1 ... will re-run process.

**Comment by Youosun** [comment]
Hey I'm still getting this issue
my go version: go1.12.7 linux/amd64
go build ./...
go: downloading github.com/apache/thrift v0.12.0
go: downloading golang.org/x/text v0.3.0
verifying github.com/apache/thrift@v0.12.0: checksum mismatch
	downloaded: h1:pODnxUFNcjP9UTLZGTdeh+j16A8lJbRvD3rOtrk/7bs=
	go.sum:     h1:ymFY8b00T66exzV1OxAnIA8mawFjPyH6l0wjuv8zTxY=
make: *** [build] 错误 1

Please suggest.

**Comment by Youosun** [comment]
> Hey I'm still getting this issue
> my go version: go1.12.7 linux/amd64
> go build ./...
> go: downloading github.com/apache/thrift v0.12.0
> go: downloading golang.org/x/text v0.3.0
> verifying github.com/apache/thrift@v0.12.0: checksum mismatch
> downloaded: h1:pODnxUFNcjP9UTLZGTdeh+j16A8lJbRvD3rOtrk/7bs=
> go.sum: h1:ymFY8b00T66exzV1OxAnIA8mawFjPyH6l0wjuv8zTxY=
> make: *** [build] 错误 1
> 
> Please suggest.

I think it's a go 1.11 version problem. But I have update it to v.1.12.
