### ISSUE TITLE
Support for https proxy

### ISSUE THREAD

**Issue by paulsjohnson91** [uber/kraken#96]
I'm trying to proxy to a private https nexus repository but http seems to be hardcoded for the tagquery

**Comment by paulsjohnson91** [comment]
Update: most of the query strings are hardcoded to http, when manually updating all of these hardcoded string I got it to work with a https repository but also the http client get function seems to override to http which also had to be updated.

**Comment by codygibb** [comment]
So internally, all urls are hardcoded as http. We use the `SendTLS` option in `package httputil` to enable https, which swaps http for https:

```
// SendTLS sets the transport with TLS config for the HTTP client.
func SendTLS(config *tls.Config) SendOption {
	return func(o *sendOptions) {
		if config == nil {
			return
		}
		o.transport = &http.Transport{TLSClientConfig: config}
		o.url.Scheme = "https"
	}
}
```

**Comment by evelynl94** [comment]
I think as long as you have the correct tls config it should do the right thing. For example, in the example devcluster we pull from dockerhub using https://github.com/uber/kraken/blob/master/examples/devcluster/config/build-index/development.yaml#L8

**Comment by paulsjohnson91** [comment]
Yes you're right I was seeing the request in the logs as http because it was falling back to http due to me not adding the correct certificates to the build for my nexus. Thanks for the help

**Comment by yiranwang52** [comment]
So the problem is solved?
